#:schema node_modules/wrangler/config-schema.json

name = "smarttask-ai"
main = "src/server.ts"
compatibility_date = "2025-03-14"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[durable_objects]
bindings = [
  { name = "SmartTaskAgent", class_name = "SmartTaskAgent" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SmartTaskAgent"]

[assets]
directory = "./dist/client"
binding = "ASSETS"
